### ISSUE TITLE
Provide a way to access other podcasts not on Itunes or Soundcloud

### ISSUE THREAD

**Issue by moldach** [erramirez/podr#1]
It would be nice to investigate podcasts from other sources like [BBC](http://www.bbc.co.uk/podcasts) or [Podomatic](https://www.podomatic.com/)

**Comment by erramirez** [comment]
@moldach any podcast with an accessible rss url should be able to be read by the `readpod` function. You should be able to find them using the *Subscribe* buttons/options. Just look for "RSS" or "Subscribe to RSS feed." 

However, I do see some issues with the BBC and Podomatic podcasts and working with the `cleanpod` function as their *duration* is returned in seconds and not hh:mm:ss (1153 instead of 00:19:13). 

I've opened [issue #2](https://github.com/erramirez/podr/issues/2) to address this.

**Comment by erramirez** [comment]
Issue #2 has been closed. BBC and Podomatic podcasts should work now with the `cleanpod` function.
